default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: <%= ENV['HOME'] %>/.durt/db/development.sqlite3

test: &test
  <<: *default
  database: <%= ENV['HOME'] %>/.durt/db/test.sqlite3

production:
  <<: *default
  database: <%= ENV['HOME'] %>/.durt/db/production.sqlite3

sample:
  <<: *default
  database: db/sample.sqlite3
